### ISSUE TITLE
VCell logs are not valid

### ISSUE THREAD

**Issue by jonrkarr** [virtualcell/vcell#110]
Successful tasks, documents, etc should have `exception: null` rather than `exception: {message: null, type: null}`

Until now the test suite has reported errors with logs as warnings (see [warnings](https://github.com/biosimulators/Biosimulators/issues/464#issuecomment-965336371) for last VCell validation). I just changed this to report errors now that VCell produces logs and we're no longer relying on tellurium to execute SED-ML.

## Current log
```yaml
duration: 28
exception: null
output: 'Processing Parmar2017_Deficient_Rich_tracer.sedml. '
sedDocuments:
- duration: null
  exception:
    message: null
    type: null
  location: Parmar2017_Deficient_Rich_tracer.sedml
  output: 'Initializing sedml document... done. Successful translation of SED-ML file.
    Starting simulate all tasks... done. Generating outputs... done. '
  outputs:
  - curves:
    - id: curve_FeDuo
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3b
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeBM
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3c
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeRBC
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3d
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeLiver
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3e
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeSpleen
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3f
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeRest
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3g
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeOutside
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3h
    output: null
    skipReason: null
    status: SUCCEEDED
  - dataSets:
    - id: data_set_time
      status: SUCCEEDED
    - id: data_set_Fe1Tf
      status: SUCCEEDED
    - id: data_set_Fe1Tf_0
      status: SUCCEEDED
    - id: data_set_Fe2Tf
      status: SUCCEEDED
    - id: data_set_Fe2Tf_
      status: SUCCEEDED
    - id: data_set_Fe2Tf_0
      status: SUCCEEDED
    - id: data_set_FeBM
      status: SUCCEEDED
    - id: data_set_FeBM_0
      status: SUCCEEDED
    - id: data_set_FeDuo
      status: SUCCEEDED
    - id: data_set_FeDuo_0
      status: SUCCEEDED
    - id: data_set_FeLiver
      status: SUCCEEDED
    - id: data_set_FeLiver_0
      status: SUCCEEDED
    - id: data_set_FeOutside
      status: SUCCEEDED
    - id: data_set_FeRBC
      status: SUCCEEDED
    - id: data_set_FeRBC_0
      status: SUCCEEDED
    - id: data_set_FeRest
      status: SUCCEEDED
    - id: data_set_FeRest_0
      status: SUCCEEDED
    - id: data_set_FeSpleen
      status: SUCCEEDED
    - id: data_set_FeSpleen_0
      status: SUCCEEDED
    - id: data_set_Hepcidin
      status: SUCCEEDED
    - id: data_set_NTBI
      status: SUCCEEDED
    - id: data_set_NTBI_0
      status: SUCCEEDED
    - id: data_set_Tf
      status: SUCCEEDED
    duration: null
    exception: null
    id: report
    output: null
    skipReason: null
    status: SUCCEEDED
  skipReason: null
  status: SUCCEEDED
  tasks:
  - algorithm: KISAO_0000019
    duration: 1
    exception:
      message: null
      type: null
    id: task_1
    output: 'Initializing simulation... done. Starting simulation... done. '
    simulatorDetails: null
    skipReason: null
    status: SUCCEEDED
skipReason: null
status: SUCCEEDED
```

## Corrected log
```yaml
duration: 28
exception: null
output: 'Processing Parmar2017_Deficient_Rich_tracer.sedml. '
sedDocuments:
- duration: null
  exception: null
  location: Parmar2017_Deficient_Rich_tracer.sedml
  output: 'Initializing sedml document... done. Successful translation of SED-ML file.
    Starting simulate all tasks... done. Generating outputs... done. '
  outputs:
  - curves:
    - id: curve_FeDuo
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3b
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeBM
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3c
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeRBC
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3d
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeLiver
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3e
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeSpleen
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3f
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeRest
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3g
    output: null
    skipReason: null
    status: SUCCEEDED
  - curves:
    - id: curve_FeOutside
      status: SUCCEEDED
    duration: null
    exception: null
    id: Figure_3h
    output: null
    skipReason: null
    status: SUCCEEDED
  - dataSets:
    - id: data_set_time
      status: SUCCEEDED
    - id: data_set_Fe1Tf
      status: SUCCEEDED
    - id: data_set_Fe1Tf_0
      status: SUCCEEDED
    - id: data_set_Fe2Tf
      status: SUCCEEDED
    - id: data_set_Fe2Tf_
      status: SUCCEEDED
    - id: data_set_Fe2Tf_0
      status: SUCCEEDED
    - id: data_set_FeBM
      status: SUCCEEDED
    - id: data_set_FeBM_0
      status: SUCCEEDED
    - id: data_set_FeDuo
      status: SUCCEEDED
    - id: data_set_FeDuo_0
      status: SUCCEEDED
    - id: data_set_FeLiver
      status: SUCCEEDED
    - id: data_set_FeLiver_0
      status: SUCCEEDED
    - id: data_set_FeOutside
      status: SUCCEEDED
    - id: data_set_FeRBC
      status: SUCCEEDED
    - id: data_set_FeRBC_0
      status: SUCCEEDED
    - id: data_set_FeRest
      status: SUCCEEDED
    - id: data_set_FeRest_0
      status: SUCCEEDED
    - id: data_set_FeSpleen
      status: SUCCEEDED
    - id: data_set_FeSpleen_0
      status: SUCCEEDED
    - id: data_set_Hepcidin
      status: SUCCEEDED
    - id: data_set_NTBI
      status: SUCCEEDED
    - id: data_set_NTBI_0
      status: SUCCEEDED
    - id: data_set_Tf
      status: SUCCEEDED
    duration: null
    exception: null
    id: report
    output: null
    skipReason: null
    status: SUCCEEDED
  skipReason: null
  status: SUCCEEDED
  tasks:
  - algorithm: KISAO_0000019
    duration: 1
    exception: null
    id: task_1
    output: 'Initializing simulation... done. Starting simulation... done. '
    simulatorDetails: null
    skipReason: null
    status: SUCCEEDED
skipReason: null
status: SUCCEEDED
```
